# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# application configuration
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
application.name = Application: 'SE-2 Freerider' Car Reservation System
application.version = 1.0.0
application.args = A BB CCC
application.greeting = true
# application.run = CustomerRunner, DatabaseRunner
application.run = CustomerRunner

# database configuration
db.url = jdbc:h2:mem:freerider
# db.url = jdbc:h2:file:./.database/h2
db.user = sa
db.password = 
