DROP TABLE if exists CUSTOMER;

CREATE TABLE if not exists CUSTOMER (
  -- ID INT GENERATED BY DEFAULT AS IDENTITY, -- MySQL does not support IDENTITY
  ID BIGINT AUTO_INCREMENT not null,            -- use AUTO_INCREMENT instead
  NAME VARCHAR(60) not null,
  FIRSTNAME VARCHAR(60) default null,
  CONTACT VARCHAR(60) default null,
  STATUS enum('Active', 'InRegistration', 'Terminated') default null,
  STATUS_CHANGE TIMESTAMP default null,
  -- 
  PRIMARY KEY (ID)
);
