# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# 'log4j2.properties' defines the configuration of the logging system
# used in the program, see:
# https://logging.apache.org/log4j/2.x/manual/config-intro.html
# 
# This 'log4j2.properties' file defines:
# - loggers used in the program, e.g. the 'db-logger'
# - filtering (by levels) and distribution of log messages to
#   appenders (here: 'db-console-appender' and 'db-file-appender')
# - appenders
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# configuration of the 'app-logger'-logger: OFF, FATAL, ERROR, WARN,
# INFO, DEBUG, TRACE, ALL
logger.app.name = app-logger
logger.app = OFF, app-console-appender
logger.app.additivity = false
appender.app-con.name = app-console-appender
appender.app-con.type = Console
appender.app-con.layout.type = PatternLayout
appender.app-con.layout.pattern = --> %m%n


# configuration of the 'db-logger'-logger
logger.db-logger.name = db-logger
# 
# distribution to appenders according to log levels:
# OFF, FATAL, ERROR, WARN, INFO, DEBUG, TRACE, ALL
logger.db-logger = ALL, db-console-appender, db-file-appender
# 
# configure to not inherit parent logger properties
logger.db-logger.additivity = false


# Console appender used by 'db-logger'
appender.db-con.name = db-console-appender
appender.db-con.type = Console
appender.db-con.layout.type = PatternLayout
appender.db-con.layout.pattern = %m%n
# Filter passes messages with level INFO or higher (INFO, WARN, ERROR, FATAL)
appender.db-con.filter.threshold.type = ThresholdFilter
appender.db-con.filter.threshold.level = INFO
# 
# Filter DENIES any message with level INFO or higher (INFO, WARN, ERROR, FATAL)
# It sets onMatch to DENY and onMismatch to NEUTRAL, allowing lower levels to pass
# appender.db-con.filter.threshold.type = ThresholdFilter
# appender.db-con.filter.threshold.level = INFO
# appender.db-con.filter.threshold.onMatch = DENY
# appender.db-con.filter.threshold.onMismatch = NEUTRAL


# Rolling file appender used by 'app-logger' in 'logs' directory
appender.db-file.name = db-file-appender
appender.db-file.append = false
appender.db-file.type = RollingRandomAccessFile
appender.db-file.fileName = logs/db-log.log
appender.db-file.filePattern = logs/db-log.log.%i
appender.db-file.immediateFlush = true
appender.db-file.layout.type = PatternLayout
appender.db-file.layout.pattern=[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n
appender.db-file.policies.type = Policies
# Filter passes all messages
appender.db-file.filter.threshold.type = ThresholdFilter
appender.db-file.filter.threshold.level = ALL

# # log4j logging during initialization
# log levels: OFF, FATAL, ERROR, WARN, INFO, DEBUG, TRACE, ALL
# status = OFF
