package mvn.jdbc.datamodel;

import java.time.LocalDateTime;

import lombok.*;
import lombok.experimental.Accessors;

/**
 * Class of a {@link Customer} entity corresponding to table {@code CUSTOMER}
 * in the database schema:
 * <pre>
 * CREATE TABLE if not exists CUSTOMER (
 *   -- ID INT GENERATED BY DEFAULT AS IDENTITY,  -- MySQL does not support IDENTITY
 *   ID BIGINT AUTO_INCREMENT not null,           -- use AUTO_INCREMENT instead
 *   NAME VARCHAR(60) not null,
 *   FIRSTNAME VARCHAR(60) default null,
 *   CONTACT VARCHAR(60) default null,
 *   STATUS enum('Active', 'InRegistration', 'Terminated') default null,
 *   STATUS_CHANGE TIMESTAMP default null,
 *   PRIMARY KEY (ID)
 * );
 * </pre>
*/
@Getter
@Setter
@AllArgsConstructor
@RequiredArgsConstructor
@ToString
@Accessors(fluent=true, chain=true)
public class Customer {

    private final long id;

    /**
     * last name getter
     * -- SETTER --
     * last name setter
     * @param name last name attribute to set
     */
    private String name;
    private String firstName;
    private String contact;
    private Status status;
    private LocalDateTime statusChange;

    /**
     * Status of {@link Customer}
     */
    public enum Status {

        /** active, can conduct business */
        Active,

        /** in the registration process */
        InRegistration,

        /** unregistered or terminated, can no longer conduct business */
        Terminated,

        /** inital state in the database */
        Null
    };
}
