package mvn.jdbc.datamodel;

import java.time.LocalDateTime;

import lombok.*;
import lombok.experimental.Accessors;

/**
 * Class of a {@link Customer} entity corresponding to table {@code CUSTOMER}
 * in the database schema:
 * <pre>
 * CREATE TABLE if not exists CUSTOMER (
 *   -- ID INT GENERATED BY DEFAULT AS IDENTITY,  -- MySQL does not support IDENTITY
 *   ID BIGINT AUTO_INCREMENT not null,           -- use AUTO_INCREMENT instead
 *   NAME VARCHAR(60) not null,
 *   FIRSTNAME VARCHAR(60) default null,
 *   CONTACT VARCHAR(60) default null,
 *   STATUS enum('Active', 'InRegistration', 'Terminated') default null,
 *   STATUS_CHANGE TIMESTAMP default null,
 *   PRIMARY KEY (ID)
 * );
 * </pre>
*/
@Getter
@Setter
@AllArgsConstructor
@RequiredArgsConstructor
@ToString
@Accessors(fluent=true, chain=true)
public class Customer {

    /**
     * -- GETTER --
     * unique {@link Customer} id generated by the database
     * {@code id} attribute getter
     * @return {@code id} attribute
     */
    private final long id;

    /**
     * -- GETTER --
     * last {@code name} attribute getter
     * @return last {@code id} attribute
     * 
     * -- SETTER --
     * last {@code name} attribute setter
     * @param name last {@code name} attribute to set
     * @return chainable self-reference
     */
    private String name;                // customer last name
    private String firstName;           // customer first names
    private String contact;             // customer contact
    private Status status;              // customer status
    private LocalDateTime statusChange; // time of last status change

    /**
     * Status of {@link Customer}
     */
    public enum Status {

        /** active, can conduct business */
        Active,

        /** in the registration process */
        InRegistration,

        /** unregistered or terminated, can no longer conduct business */
        Terminated,

        /** inital state in the database */
        Null
    };
}
