package mvn.jdbc.application;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.util.Spliterators.AbstractSpliterator;
import java.util.function.Consumer;
import java.util.stream.*;
import org.apache.logging.log4j.*;
import lombok.Builder;

/**
 * Database builder to create a database with schema and initial data.
 * Builder uses {@code lombok's @Builder}.
 * <p>
 * The example shows how a simple (H2) in-memory database is created with
 * schema and some initial data loaded before a query is executed:
 * <pre>
 * 
 * Database db = Database.builder()
 *     // 
 *     .db_url("jdbc:h2:mem:freerider")
 *     // .db_url("jdbc:h2:file:./.database/h2")
 *     .db_user("sa")
 *     .db_password("")
 *     // 
 *     // .schema("file:src/resources/db-schema.sql")
 *     .schema(
 *         // "CREATE SCHEMA IF NOT EXISTS TESTDB;" +
 *         // "USE TESTDB;\n" +
 *         // "DROP TABLE IF EXISTS CUSTOMER;\n" +
 *         // 
 *         "CREATE TABLE if not exists CUSTOMER (" +
 *         // "  ID INT GENERATED BY DEFAULT AS IDENTITY," +   // MySQL does not support IDENTITY
 *         "  ID BIGINT AUTO_INCREMENT not null," +            // use AUTO_INCREMENT instead
 *         "  NAME VARCHAR(60) not null," +
 *         "  FIRSTNAME VARCHAR(60) default null," +
 *         "  CONTACT VARCHAR(60) default null," +
 *         "  STATUS enum('Active', 'InRegistration', 'Terminated') default null," +
 *         "  STATUS_CHANGE TIMESTAMP default null," +
 *         "  PRIMARY KEY (ID)" +
 *         ");" +
 *         // 
 *         // "\nALTER TABLE CUSTOMER AUTO_INCREMENT = 100;" +
 *         "\nALTER TABLE CUSTOMER ALTER COLUMN ID RESTART WITH 100;"
 *     )
 *     // .data("file:src/resources/db-schema.sql")
 *     .data(
 *         "INSERT INTO CUSTOMER(FIRSTNAME, NAME, CONTACT, STATUS, STATUS_CHANGE) VALUES " +
 *             "('Eric',   'Meyer',    'eme22@gmail.com',      'Active',         {ts '2024-06-04 12:35'})," +
 *             "('Sommer', 'Tina',     '+49 030 22458 29425',  'Active',         {ts '2025-10-07 10:28'})," +
 *             "('Schulze', 'Tim',     '+49 171 2358124',      'Active',         {ts '2024-12-28 18:00'})," +
 *     )
 *     .build();
 * 
 * var dbcon = db.connect().get();
 * // 
 * // Database-access in JDBC occurs through (SQL-)'statements'
 * try(Statement stmt = dbcon.createStatement()) {
 *     // 
 *     // send SQL-Query to database, obtain 'ResultSet' with results
 *     ResultSet rs = stmt.executeQuery("SELECT * FROM CUSTOMER");
 *     // 
 *     // iterate over ResultSet, extract row attributes and output to table
 *     int rowCounter = 0;
 *     while(rs.next()) {
 *         var id = Long.toString(rs.getLong("ID"));
 *         var name = rs.getString("NAME");
 *         var firstName = rs.getString("FIRSTNAME");
 *         var contact = rs.getString("CONTACT");
 *         var status = rs.getString("STATUS");
 *         var statusChange = rs.getTimestamp("STATUS_CHANGE").toLocalDateTime().format(dtf);
 *         // 
 *         // print result values into table
 *         customerTable.row(id, name, firstName, contact, status, statusChange);
 *     }
 *     // 
 * } catch (SQLException e) {
 *     log.error(String.format("Error reading all records from database CUSTOMER, %s", e.getMessage()));
 * }
 * 
 * Output:
 * +-----+---------- +-----------+---------------------+--------+------------------+
 * |  ID | NAME      | FIRSTNAME | CONTACT             | STATUS | STATUS_CHANGE    |
 * +-----+---------- +-----------+---------------------+--------+------------------+
 * | 100 | Eric      | Meyer     | eme22@gmail.com     | Active | 2024-06-04 12:35 |
 * | 101 | Sommer    | Tina      | +49 030 22458 29425 | Active | 2025-10-07 10:28 |
 * | 102 | Schulze   | Tim       | +49 171 2358124     | Active | 2024-12-28 18:00 |
 * +-----+---------- +-----------+---------------------+--------+------------------+
 * </pre>
 */
@Builder
public class Database {
    private String db_url;
    private String db_user;
    private String db_password;

    private Connection dbcon;
    private static final Logger log = LogManager.getLogger("db-logger");
    private static ResultSet emptyResultSet = null;

    /**
     * Map row from a {@link ResultSet} to data object of type {@link T}.
     * @param <T> type {@link T} to map
     */
    @FunctionalInterface
    public interface RowMapper<T> {

        /**
         * Create object of type {@link T} from {@link ResultSet}
         * @param rs {@link ResultSet} mapped to type {@link T}
         * @return object of type {@link T} mapped from {@link ResultSet}
         * @throws SQLException thrown in case of error
         */
        T mapRow(ResultSet rs) throws SQLException;
    }

    /**
     * {@link Consumer} interface for {@link PreparedStatement} that
     * absorbs {@link SQLException} in calling code.
     */
    @FunctionalInterface
    public interface Preparer {

        /**
         * Method that invokes lambda expression
         * @param ps {@link PreparedStatement}
         * @throws SQLException
         */
        void accept(PreparedStatement ps) throws SQLException;
    }


    /**
     * Builder class for {@link Database} object.
     * <p>
     * Extension to @lombok.Generated builder class.
     * https://stackoverflow.com/questions/74800046/how-to-override-lombok-builder-method
     */
    public static class DatabaseBuilder {
        private Database db = null;
        private boolean schemaBuilt = false;

        /**
         * Return built database.
         * @return built database
         */
        public Database build() {
            return db();
        }

        /**
         * Creates and returns {@link Database} instance {@code db}.
         * @return {@link Database} instance
         */
        Database db() {
            return Optional.ofNullable(this.db).orElseGet(() -> {
                log.trace("database instance created");
                return this.db = new Database(db_url, db_user, db_password, null);
            });
        }

        /**
         * Load schema as build-step.
         * @param schema schema (as <i>String</i>) or file name from where schema is loaded (starting with {@code "file:"})
         * @return chainable self-reference
         */
        public DatabaseBuilder schema(String schema) {
            if(schema != null && schema.length() > 0) {
                db().connect().ifPresent(dbcon -> {
                    try {
                        List<String> tablesFound = new ArrayList<>();
                        ResultSet rs = dbcon.createStatement().executeQuery("SHOW TABLES;");
                        while(rs.next()){
                            var tbl = rs.getString(1);
                            log.trace(String.format("found table: \'%s\'", tbl));
                            tablesFound.add(tbl);
                        }
                        if(tablesFound.size()==0) {
                            for(var sqlStmt : schema.split("\n")) {
                                var schemaContent = sqlStmt;
                                if(schema.startsWith("file:".toLowerCase())) {
                                    schemaContent = readFile(schema.substring("file:".length())).toString();
                                }
                                log.info(String.format("schema: \'%s\'", schemaContent));
                                // 
                                Statement stmt = dbcon.createStatement();
                                stmt.executeUpdate(schemaContent);
                            }
                            schemaBuilt = true;
                        }
                    } catch (SQLException e) {
                        log.error("error loading database schema, " + e.getMessage());
                    }
                });
            }
            return this;
        }

        /**
         * Load initial data as build-step.
         * @param sql sql (as <i>String</i>) or file name from where data is loaded (starting with {@code "file:"})
         * @return chainable self-reference
         */
        public DatabaseBuilder data(String sql) {
            if(schemaBuilt && sql != null && sql.length() > 0) {
                db().connect().ifPresent(dbcon -> {
                    int numRowsInserted = 0;
                    var data = sql;
                    if(sql.startsWith("file:".toLowerCase())) {
                        log.info(String.format("load data: \'%s\'", sql));
                        data = readFile(sql.substring("file:".length())).toString();
                    }
                    log.info(String.format("%s: \'%s\'", sql.toUpperCase().contains("INSERT")? "insert" : "update", data));
                    // 
                    try(PreparedStatement ps = dbcon.prepareStatement(data, Statement.RETURN_GENERATED_KEYS)) {
                        numRowsInserted = ps.executeUpdate();
                        ResultSet rs = ps.getGeneratedKeys();
                        while(rs.next()) {
                            long id = rs.getLong(1);
                            log.trace(String.format("inserted record with id: %d", id));
                        }
                        log.info(String.format("(%d rows) inserted", numRowsInserted));
                    // 
                    } catch(SQLException e) {
                        log.error("error loading database data, " + e.getMessage());
                    }
                });
            }
            return this;
        }

        /**
         * Read file and return in {@link StringBuilder}.
         * @param fileName of file to read
         * @return file content in {@link StringBuilder}
         */
        private StringBuilder readFile(String fileName) {
            StringBuilder sb = new StringBuilder();
            try (BufferedReader br = new BufferedReader(new FileReader(fileName))) {
                String line;
                while ((line = br.readLine()) != null) {
                    sb.append(line).append("\n");
                }
            } catch (IOException e) {
                log.error(String.format("error reading: \'%s\', ", fileName, e.getMessage()));
            }
            return sb;
        }
    }

    /**
     * Open connection to the database, if not already open.
     * @return database {@link Connection} if connection was opened
     */
    public Optional<Connection> connect() {
        if(argsNotNull(db_url, "db_url")) {
            try {
                if(dbcon==null || dbcon.isClosed()) {
                    this.dbcon = DriverManager.getConnection(db_url, db_user, db_password);
                    log.trace(String.format(
                        "database connection opened using: \'%s\', (user: \'%s\', password: \'%s\')",
                        db_url, db_user, db_password));
                    // 
                    // // emptyResultSet is an alternative return value for failed queries
                    if(emptyResultSet==null) {
                        Statement stmt = dbcon.createStatement();
                        emptyResultSet = stmt.executeQuery("SELECT 1 WHERE FALSE");
                        if(emptyResultSet==null)
                            throw new SQLException("could not create empty ResultSet");
                    }
                }
            } catch (SQLException e) {
                this.dbcon = null;
                var msg = "database connection exception using: \'%s\', (user: \'%s\', password: \'%s\'), %s";
                if(e.getMessage().contains("InvalidPathException")) {
                    this.db_url = null;
                    log.fatal(String.format(msg, db_url, db_user, db_password, "\"InvalidPathException\""));
                } else {
                    log.error(String.format(msg, db_url, db_user, db_password, e.getMessage()));
                }
            }
        }
        return Optional.ofNullable(this.dbcon);
    }

    /**
     * Close open database connection.
     * @return chainable self-reference
     */
    public Database close() {
        try {
            if(argsNotNull(dbcon, "dbcon") && ! dbcon.isClosed()) {
                dbcon.close();
                log.trace("database connection closed");
            } else {
                log.trace("database connection has already been closed");
            }
        } catch (SQLException e) {
            log.error(String.format("exception closing connection: %s", e.getMessage()));
        }
        return this;
    }

    /**
     * Execute {@code SQL SELECT} query with {@link PreparedStatement}, apply
     * {@link RowMapper}{@code <T>} to {@link ResultSet} and return as
     * {@link Stream}{@code <T>}.
     * 
     * @param <T> generic type to which a returned row is mapped
     * @param sql {@code SQL SELECT} query statement
     * @param rowMapper invoked for each row to map row to type {@code <T>}
     * @return records returned from the query as {@link Stream}{@code <T>}
     */
    public <T> Stream<T> query(String sql, RowMapper<T> rowMapper) {
        if(argsNotNull(sql, "sql", rowMapper, "rowMapper") && connect().isPresent()) {
            try {
                Statement stmt = dbcon.createStatement();
                log.trace(String.format("query: \'%s\'", sql));
                ResultSet rs = stmt.executeQuery(sql);
                return StreamSupport.stream(
                    new ResultSetSpliterator<>(rs, row -> rowMapper.mapRow(row)), false);
            // 
            } catch (SQLException e) {
                log.error(String.format("query exception: \'%s\', %s", sql, e.getMessage()));
            }
        }
        return Stream.of();
    }

    /**
     * Execute {@code SQL SELECT} query with {@link PreparedStatement}, apply
     * {@link RowMapper}{@code <T>} to {@link ResultSet} and return as
     * {@link Stream}{@code <T>}.
     * 
     * @param <T> generic type to which a returned row is mapped
     * @param sql {@code SQL SELECT} query statement
     * @param preparedStatement to substitute {@code '?'} placeholders in {@code sql}
     * @param rowMapper invoked for each row to map row to type {@code <T>}
     * @return records returned from the query as {@link Stream}{@code <T>}
     */
    public <T> Stream<T> query(String sql, Preparer preparedStatement, RowMapper<T> rowMapper) {
        if(argsNotNull(sql, "sql", rowMapper, "rowMapper") && connect().isPresent()) {
            // try(PreparedStatement ps = dbcon.prepareStatement(sql)) {
            try {
                PreparedStatement ps = dbcon.prepareStatement(sql);
                log.trace(String.format("query: \'%s\'", sql));
                if(preparedStatement != null) {
                    preparedStatement.accept(ps);
                }
                log.trace(String.format("update: \'%s\'", ps.toString()));
                ResultSet rs = ps.executeQuery(sql);
                return StreamSupport.stream(
                    new ResultSetSpliterator<>(rs, row -> rowMapper.mapRow(row)), false);
            // 
            } catch (SQLException e) {
                log.error(String.format("query exception: \'%s\', %s", sql, e.getMessage()));
            }
        }
        return Stream.of();
    }

    /**
     * Execute {@code SQL UPDATE} and {@code INSERT}.
     * @param sql {@code SQL UPDATE} and {@code INSERT} operation
     * @return chainable self-reference
     */
    public Database update(String sql) {
        return update(sql, null);
    }

    /**
     * Execute {@code UPDATE} and {@code INSERT} with {@link PreparedStatement}.
     * 
     * @param sql {@code SQL UPDATE} and {@code INSERT} operation
     * @param preparedStatement to substitute {@code '?'} placeholders in {@code sql}
     * @return chainable self-reference
     */
    public Database update(String sql, Preparer preparedStatement) {
        if(argsNotNull(sql, "sql") && connect().isPresent()) {
            try(PreparedStatement ps = dbcon.prepareStatement(sql)) {
                log.info(String.format("update: \'%s\'", sql));
                if(preparedStatement != null) {
                    preparedStatement.accept(ps);
                }
                log.info(String.format("update: \'%s\'", ps.toString()));
                int rowsUpdated = ps.executeUpdate();
                log.info(String.format("(%d rows) updated", rowsUpdated));
            // 
            } catch(SQLException e) {
                log.error("error loading database data, " + e.getMessage());
            }
        }
        return this;
    }

    /**
     * {@link AbstractSpliterator}{@code <T>} to make {@link ResultSet} streamable.
     * https://www.javacodegeeks.com/processing-jdbc-resultset-with-stream-api.html
     */
    private class ResultSetSpliterator<T> extends AbstractSpliterator<T> {
        private final ResultSet resultSet;
        private final RowMapper<T> rowMapper;

        public ResultSetSpliterator(ResultSet resultSet, RowMapper<T> rowMapper) {
            super(Long.MAX_VALUE, ORDERED | NONNULL);
            this.resultSet = resultSet;
            this.rowMapper = rowMapper;
        }

        @Override
        public boolean tryAdvance(java.util.function.Consumer<? super T> action) {
            try {
                if( ! resultSet.next()) return false;
                action.accept(rowMapper.mapRow(resultSet));
                return true;
            } catch (SQLException e) {
                throw new RuntimeException("Error processing ResultSet", e);
            }
        }
    }

    /**
     * Validate arguments and write log if one of the arguments is {@code null}.
     * @param args arguments as sequence of {@code [arg, argname]} pairs
     * @return true if no arguments was {@code null}
     */
    private boolean argsNotNull(Object... args) {
        for(int i=0; i < args.length; i+=2) {
            if(args[i]==null) {
                log.error(String.format("null argument: %s", args[i+1]));
                return false;
            }
        }
        return true;
    }
}
