package mvn.jdbc.application;

import java.sql.*;
import java.time.format.DateTimeFormatter;
import org.apache.logging.log4j.*;

/**
 * Demo that creates {@link mvn.jdbc.datamodel.Customer} objects
 * in the database.
 * <pre>
 * +------+----------------+----------------+------------------------+
 * |   ID | NAME           | FIRSTNAME      | CONTACT                |
 * +------+----------------+----------------+------------------------+
 * |  100 | Eric           | Meyer          | eme22@gmail.com        |
 * |  101 | Sommer         | Tina           | +49 030 22458 29425    |
 * |  102 | Schulze        | Tim            | +49 171 2358124        |
 * |  103 | Brinkmann      | Tobias         | +49 030 662465724      |
 * +------+----------------+----------------+------------------------+
 * </pre>
 */
public class DatabaseRunner implements Application.Runnable {

    private final Logger log = LogManager.getLogger("db-logger");

    @Override
    public void run(ApplicationContext context) {
        // 
        DateTimeFormatter dtf = context.dtf();
        var table = context.customerTableFormatterBuilder().build();
        // 
        Database db = Database.builder()
            // 
            .db_url("jdbc:h2:mem:freerider")        // in-memory database (volatile)
            // .db_url("jdbc:h2:file:./.database/h2")  // persistent database
            .db_user("sa")
            .db_password("")
            // 
            // .db_url("jdbc:mysql://localhost:3306/TESTDB")
            // .db_user("root")
            // .db_password("")
            // 
            // .schema("file:src/main/resources/db-schema.sql")
            // .schema("file:src/main/resources/db-schema-customer.sql")
            .schema(
                // "CREATE SCHEMA IF NOT EXISTS TESTDB;" +
                // "USE TESTDB;\n" +
                // "DROP TABLE IF EXISTS CUSTOMER;\n" +
                // 
                "CREATE TABLE if not exists CUSTOMER (" +
                // "  ID INT GENERATED BY DEFAULT AS IDENTITY," +   // MySQL does not support IDENTITY
                "  ID INT AUTO_INCREMENT not null," +               // use AUTO_INCREMENT instead
                "  NAME VARCHAR(60) not null," +
                "  FIRSTNAME VARCHAR(60) default null," +
                "  CONTACT VARCHAR(60) default null," +
                "  STATUS enum('Active', 'InRegistration', 'Terminated') default null," +
                "  STATUS_CHANGE TIMESTAMP default null," +
                "  PRIMARY KEY (ID)" +
                ");" +
                // 
                // "\nALTER TABLE CUSTOMER AUTO_INCREMENT = 100;" +
                "\nALTER TABLE CUSTOMER ALTER COLUMN ID RESTART WITH 100;"
            )
            // 
            // .data("file:src/main/resources/db-data.sql")
            .data(
                "ALTER TABLE CUSTOMER ALTER COLUMN ID RESTART WITH 100;" +
                "" +
                "INSERT INTO CUSTOMER(FIRSTNAME, NAME, CONTACT, STATUS, STATUS_CHANGE) VALUES " +
                    "('Eric',   'Meyer',    'eme22@gmail.com',      'Active',         {ts '2024-06-04 12:35'})," +
                    "('Sommer', 'Tina',     '+49 030 22458 29425',  'Active',         {ts '2025-10-07 10:28'})," +
                    "('Schulze', 'Tim',     '+49 171 2358124',      'Active',         {ts '2024-12-28 18:00'})," +
                    "('Brinkmann', 'Tobias','+49 030 662465724',    'InRegistration', {ts '2025-11-28 12:18'})," +
                    "('Tony',   'Allister', '+49 030 24253134',     'Active',         {ts '2023-02-10 18:00'})," +
                    "('Sandra', 'Ohlstadt', 'ohlst@gmail.com',      'Active',         {ts '2023-08-17 18:00'})," +
                    "('Erica',  'Gronemann', 'gron@gmx.de',         'InRegistration', {ts '2022-02-26 07:02'})," +
                    "('Khaleed', 'Samadi',   '-',                   'Active',         {ts '2020-09-24 18:00'})," +
                    "('Igor',   'Medwedev', 'gopnik@bht-berlin.de', 'InRegistration', {ts '2025-11-28 23:26'})"
            )
            .build();
        /*
         * db object has been built and can now be used.
         */

        // 
        // db.update("UPDATE CUSTOMER SET STATUS_CHANGE=?", ps -> {
        //     LocalDateTime ldt = LocalDateTime.parse("2025-11-20 00:00:00", dtfsec);
        //     ps.setTimestamp(1, java.sql.Timestamp.valueOf(ldt));
        // });
        // 
        // 'dbcon' is the database connection object
        var dbcon = db.connect().get();
        // 
        // Database-access in JDBC is performed with (SQL-)'statements'
        try(Statement stmt = dbcon.createStatement()) {
            // 
            // send SQL-Query to database, obtain 'ResultSet' with results
            String sql = "SELECT * FROM CUSTOMER";
            log.info(String.format("query: \'%s\'", sql));
            ResultSet rs = stmt.executeQuery("SELECT * FROM CUSTOMER");
            // 
            table.header();
            // 
            // iterate over ResultSet, extract row attributes and output to table
            int rowCounter = 0;
            while(rs.next()) {
                var id = Long.toString(rs.getLong("ID"));
                var name = rs.getString("NAME");
                var firstName = rs.getString("FIRSTNAME");
                var contact = rs.getString("CONTACT");
                var status = rs.getString("STATUS");
                var statusChange = rs.getTimestamp("STATUS_CHANGE").toLocalDateTime().format(dtf);
                // 
                // print result values into table
                table.row(id, name, firstName, contact, status, statusChange);
                rowCounter++;
            }
            table.line().print(System.out);     // print table
            // 
            log.info(String.format("(%d rows) fetched", rowCounter));
            // 
        } catch (SQLException e) {
            log.error(String.format("Error reading all records from database CUSTOMER, %s", e.getMessage()));
        }
    }

    // try(PreparedStatement ps = dbcon.prepareStatement("SELECT * FROM CUSTOMER WHERE ID=?")) {
    //     // substitute first '?' with actual value
    //     long id = 103L;
    //     ps.setLong(1, id);
    //     // 
    //     // send SQL-Query to database, obtain 'ResultSet' with results
    //     ResultSet rs = ps.executeQuery();
    //     // 
    //     // iterate over ResultSet to extract row attributes
    //     while(rs.next()) {
    //         id = rs.getLong("ID");
    //         String firstName = rs.getString("FIRSTNAME");
    //         String name = rs.getString("NAME");
    //         // 
    //         String line = String.format("| %4d | %-20s| %-20s|", id, name, firstName);
    //         System.out.println(line);
    //     }
    //     System.out.println(hdr);
    //     // 
    // } catch (SQLException e) {
    //     System.out.println(String.format("Error reading all records from database CUSTOMER, %s", e.getMessage()));
    // }
}
